# Generated by Django 4.1.5 on 2023-01-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Day',
        ),
    ]
