# Generated by Django 4.1.5 on 2023-01-12 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=254)),
                ('section', models.CharField(choices=[('S', 'Starters'), ('E', 'Entrees'), ('D', 'Deserts')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('portion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(100)])),
                ('diet', models.CharField(choices=[('V', 'Vegan'), ('VG', 'Vegetarian'), ('DF', 'Dairy Free'), ('GF', 'Gluten Free')], max_length=2)),
                ('section', models.CharField(choices=[('S', 'Starters'), ('E', 'Entrees'), ('D', 'Deserts')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
