# Generated by Django 4.1.5 on 2023-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='diet',
            field=models.CharField(blank=True, choices=[('V', 'Vegan'), ('VG', 'Vegetarian'), ('DF', 'Dairy Free'), ('GF', 'Gluten Free')], max_length=2),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(blank=True, choices=[('S', 'Starters'), ('E', 'Entrees'), ('D', 'Deserts')], max_length=1),
        ),
    ]
