# Generated by Django 4.1.5 on 2023-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_diet_alter_menuitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('S', 'Starters'), ('E', 'Entrees'), ('D', 'Deserts')], max_length=1),
        ),
    ]
