# Generated by Django 4.1.5 on 2023-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('A', 'Appetizers'), ('M', 'Mains'), ('D', 'Deserts')], max_length=1),
        ),
    ]
